### ISSUE TITLE
Enums as types

### ISSUE THREAD

**Issue by poteirard** [mstssk/sw2dts#28]
Hi,

First of all thank you for your work and time.

If possible I think it will be good to have the enums as types. 

For example:

For this swagger file:

```yaml
correspondence:
        type: "string"
        enum:
        - "EMAIL"
        - "POST"
        - "SMS"
        - "NONE"
```
To have this type definition:

```typescript
export type correspondence = 'EMAIL' | 'POST' | 'SMS' | 'NONE';
```

What do you think?

**Comment by Finesse** [comment]
It works like you described in sw2dts 2.6.1. But there is a problem. Sw2dts converts all enum options to string. Source:

```yml
correspondence:
  enum:
    - 0
    - 1
    - 2
    - 'foo'
```

Actual result:

```ts
export type correspondence = "0" | "1" | "2" | "foo";
```

Expected result:

```ts
export type correspondence = 0 | 1 | 2 | "foo";
```
